# see: https://docs.codecov.io/docs/codecovyml-reference
codecov:
  bot: 'codecov-io'
  strict_yaml_branch: 'yaml-config'
  max_report_age: 24
  disable_default_path_fixes: no

comment:
  layout: 'reach, diff, flags, files'
  require_changes: false # if true: only post the comment if coverage changes
  require_base: no # [yes :: must have a base report to post]
  require_head: yes # [yes :: must have a head report to post]
